#include "enums.hpp"

namespace nb = nanobind;

void imgui_def_enums_auto(nb::module_ & m) {

    nb::enum_<ImGuiInputTextFlags_>(m, "ImGuiInputTextFlags")
        .value("NONE",                ImGuiInputTextFlags_None)
        .value("CharsDecimal",        ImGuiInputTextFlags_CharsDecimal)
        .value("CharsHexadecimal",    ImGuiInputTextFlags_CharsHexadecimal)
        .value("CharsUppercase",      ImGuiInputTextFlags_CharsUppercase)
        .value("CharsNoBlank",        ImGuiInputTextFlags_CharsNoBlank)
        .value("AutoSelectAll",       ImGuiInputTextFlags_AutoSelectAll)
        .value("EnterReturnsTrue",    ImGuiInputTextFlags_EnterReturnsTrue)
        .value("CallbackCompletion",  ImGuiInputTextFlags_CallbackCompletion)
        .value("CallbackHistory",     ImGuiInputTextFlags_CallbackHistory)
        .value("CallbackAlways",      ImGuiInputTextFlags_CallbackAlways)
        .value("CallbackCharFilter",  ImGuiInputTextFlags_CallbackCharFilter)
        .value("AllowTabInput",       ImGuiInputTextFlags_AllowTabInput)
        .value("CtrlEnterForNewLine", ImGuiInputTextFlags_CtrlEnterForNewLine)
        .value("NoHorizontalScroll",  ImGuiInputTextFlags_NoHorizontalScroll)
        .value("AlwaysOverwrite",     ImGuiInputTextFlags_AlwaysOverwrite)
        .value("ReadOnly",            ImGuiInputTextFlags_ReadOnly)
        .value("Password",            ImGuiInputTextFlags_Password)
        .value("NoUndoRedo",          ImGuiInputTextFlags_NoUndoRedo)
        .value("CharsScientific",     ImGuiInputTextFlags_CharsScientific)
        .value("CallbackResize",      ImGuiInputTextFlags_CallbackResize)
        .value("CallbackEdit",        ImGuiInputTextFlags_CallbackEdit)
        .value("AlwaysInsertMode",    ImGuiInputTextFlags_AlwaysInsertMode)
    ;

    nb::enum_<ImGuiTreeNodeFlags_>(m, "ImGuiTreeNodeFlags")
        .value("NONE",                 ImGuiTreeNodeFlags_None)
        .value("Selected",             ImGuiTreeNodeFlags_Selected)
        .value("Framed",               ImGuiTreeNodeFlags_Framed)
        .value("AllowItemOverlap",     ImGuiTreeNodeFlags_AllowItemOverlap)
        .value("NoTreePushOnOpen",     ImGuiTreeNodeFlags_NoTreePushOnOpen)
        .value("NoAutoOpenOnLog",      ImGuiTreeNodeFlags_NoAutoOpenOnLog)
        .value("DefaultOpen",          ImGuiTreeNodeFlags_DefaultOpen)
        .value("OpenOnDoubleClick",    ImGuiTreeNodeFlags_OpenOnDoubleClick)
        .value("OpenOnArrow",          ImGuiTreeNodeFlags_OpenOnArrow)
        .value("Leaf",                 ImGuiTreeNodeFlags_Leaf)
        .value("Bullet",               ImGuiTreeNodeFlags_Bullet)
        .value("FramePadding",         ImGuiTreeNodeFlags_FramePadding)
        .value("SpanAvailWidth",       ImGuiTreeNodeFlags_SpanAvailWidth)
        .value("SpanFullWidth",        ImGuiTreeNodeFlags_SpanFullWidth)
        .value("NavLeftJumpsBackHere", ImGuiTreeNodeFlags_NavLeftJumpsBackHere)
        .value("CollapsingHeader",     ImGuiTreeNodeFlags_CollapsingHeader)
    ;

    nb::enum_<ImGuiPopupFlags_>(m, "ImGuiPopupFlags")
        .value("NONE",                    ImGuiPopupFlags_None)
        .value("MouseButtonLeft",         ImGuiPopupFlags_MouseButtonLeft)
        .value("MouseButtonRight",        ImGuiPopupFlags_MouseButtonRight)
        .value("MouseButtonMiddle",       ImGuiPopupFlags_MouseButtonMiddle)
        .value("MouseButtonMask_",        ImGuiPopupFlags_MouseButtonMask_)
        .value("MouseButtonDefault_",     ImGuiPopupFlags_MouseButtonDefault_)
        .value("NoOpenOverExistingPopup", ImGuiPopupFlags_NoOpenOverExistingPopup)
        .value("NoOpenOverItems",         ImGuiPopupFlags_NoOpenOverItems)
        .value("AnyPopupId",              ImGuiPopupFlags_AnyPopupId)
        .value("AnyPopupLevel",           ImGuiPopupFlags_AnyPopupLevel)
        .value("AnyPopup",                ImGuiPopupFlags_AnyPopup)
    ;

    nb::enum_<ImGuiSelectableFlags_>(m, "ImGuiSelectableFlags")
        .value("NONE",             ImGuiSelectableFlags_None)
        .value("DontClosePopups",  ImGuiSelectableFlags_DontClosePopups)
        .value("SpanAllColumns",   ImGuiSelectableFlags_SpanAllColumns)
        .value("AllowDoubleClick", ImGuiSelectableFlags_AllowDoubleClick)
        .value("Disabled",         ImGuiSelectableFlags_Disabled)
        .value("AllowItemOverlap", ImGuiSelectableFlags_AllowItemOverlap)
    ;

    nb::enum_<ImGuiComboFlags_>(m, "ImGuiComboFlags")
        .value("NONE",           ImGuiComboFlags_None)
        .value("PopupAlignLeft", ImGuiComboFlags_PopupAlignLeft)
        .value("HeightSmall",    ImGuiComboFlags_HeightSmall)
        .value("HeightRegular",  ImGuiComboFlags_HeightRegular)
        .value("HeightLarge",    ImGuiComboFlags_HeightLarge)
        .value("HeightLargest",  ImGuiComboFlags_HeightLargest)
        .value("NoArrowButton",  ImGuiComboFlags_NoArrowButton)
        .value("NoPreview",      ImGuiComboFlags_NoPreview)
        .value("HeightMask_",    ImGuiComboFlags_HeightMask_)
    ;

    nb::enum_<ImGuiTabBarFlags_>(m, "ImGuiTabBarFlags")
        .value("NONE",                         ImGuiTabBarFlags_None)
        .value("Reorderable",                  ImGuiTabBarFlags_Reorderable)
        .value("AutoSelectNewTabs",            ImGuiTabBarFlags_AutoSelectNewTabs)
        .value("TabListPopupButton",           ImGuiTabBarFlags_TabListPopupButton)
        .value("NoCloseWithMiddleMouseButton", ImGuiTabBarFlags_NoCloseWithMiddleMouseButton)
        .value("NoTabListScrollingButtons",    ImGuiTabBarFlags_NoTabListScrollingButtons)
        .value("NoTooltip",                    ImGuiTabBarFlags_NoTooltip)
        .value("FittingPolicyResizeDown",      ImGuiTabBarFlags_FittingPolicyResizeDown)
        .value("FittingPolicyScroll",          ImGuiTabBarFlags_FittingPolicyScroll)
        .value("FittingPolicyMask_",           ImGuiTabBarFlags_FittingPolicyMask_)
        .value("FittingPolicyDefault_",        ImGuiTabBarFlags_FittingPolicyDefault_)
    ;

    nb::enum_<ImGuiTabItemFlags_>(m, "ImGuiTabItemFlags")
        .value("NONE",                         ImGuiTabItemFlags_None)
        .value("UnsavedDocument",              ImGuiTabItemFlags_UnsavedDocument)
        .value("SetSelected",                  ImGuiTabItemFlags_SetSelected)
        .value("NoCloseWithMiddleMouseButton", ImGuiTabItemFlags_NoCloseWithMiddleMouseButton)
        .value("NoPushId",                     ImGuiTabItemFlags_NoPushId)
        .value("NoTooltip",                    ImGuiTabItemFlags_NoTooltip)
        .value("NoReorder",                    ImGuiTabItemFlags_NoReorder)
        .value("Leading",                      ImGuiTabItemFlags_Leading)
        .value("Trailing",                     ImGuiTabItemFlags_Trailing)
    ;

    nb::enum_<ImGuiTableFlags_>(m, "ImGuiTableFlags")
        .value("NONE",                       ImGuiTableFlags_None)
        .value("Resizable",                  ImGuiTableFlags_Resizable)
        .value("Reorderable",                ImGuiTableFlags_Reorderable)
        .value("Hideable",                   ImGuiTableFlags_Hideable)
        .value("Sortable",                   ImGuiTableFlags_Sortable)
        .value("NoSavedSettings",            ImGuiTableFlags_NoSavedSettings)
        .value("ContextMenuInBody",          ImGuiTableFlags_ContextMenuInBody)
        .value("RowBg",                      ImGuiTableFlags_RowBg)
        .value("BordersInnerH",              ImGuiTableFlags_BordersInnerH)
        .value("BordersOuterH",              ImGuiTableFlags_BordersOuterH)
        .value("BordersInnerV",              ImGuiTableFlags_BordersInnerV)
        .value("BordersOuterV",              ImGuiTableFlags_BordersOuterV)
        .value("BordersH",                   ImGuiTableFlags_BordersH)
        .value("BordersV",                   ImGuiTableFlags_BordersV)
        .value("BordersInner",               ImGuiTableFlags_BordersInner)
        .value("BordersOuter",               ImGuiTableFlags_BordersOuter)
        .value("Borders",                    ImGuiTableFlags_Borders)
        .value("NoBordersInBody",            ImGuiTableFlags_NoBordersInBody)
        .value("NoBordersInBodyUntilResize", ImGuiTableFlags_NoBordersInBodyUntilResize)
        .value("SizingFixedFit",             ImGuiTableFlags_SizingFixedFit)
        .value("SizingFixedSame",            ImGuiTableFlags_SizingFixedSame)
        .value("SizingStretchProp",          ImGuiTableFlags_SizingStretchProp)
        .value("SizingStretchSame",          ImGuiTableFlags_SizingStretchSame)
        .value("NoHostExtendX",              ImGuiTableFlags_NoHostExtendX)
        .value("NoHostExtendY",              ImGuiTableFlags_NoHostExtendY)
        .value("NoKeepColumnsVisible",       ImGuiTableFlags_NoKeepColumnsVisible)
        .value("PreciseWidths",              ImGuiTableFlags_PreciseWidths)
        .value("NoClip",                     ImGuiTableFlags_NoClip)
        .value("PadOuterX",                  ImGuiTableFlags_PadOuterX)
        .value("NoPadOuterX",                ImGuiTableFlags_NoPadOuterX)
        .value("NoPadInnerX",                ImGuiTableFlags_NoPadInnerX)
        .value("ScrollX",                    ImGuiTableFlags_ScrollX)
        .value("ScrollY",                    ImGuiTableFlags_ScrollY)
        .value("SortMulti",                  ImGuiTableFlags_SortMulti)
        .value("SortTristate",               ImGuiTableFlags_SortTristate)
        .value("SizingMask_",                ImGuiTableFlags_SizingMask_)
    ;

    nb::enum_<ImGuiTableColumnFlags_>(m, "ImGuiTableColumnFlags")
        .value("NONE",                 ImGuiTableColumnFlags_None)
        .value("Disabled",             ImGuiTableColumnFlags_Disabled)
        .value("DefaultHide",          ImGuiTableColumnFlags_DefaultHide)
        .value("DefaultSort",          ImGuiTableColumnFlags_DefaultSort)
        .value("WidthStretch",         ImGuiTableColumnFlags_WidthStretch)
        .value("WidthFixed",           ImGuiTableColumnFlags_WidthFixed)
        .value("NoResize",             ImGuiTableColumnFlags_NoResize)
        .value("NoReorder",            ImGuiTableColumnFlags_NoReorder)
        .value("NoHide",               ImGuiTableColumnFlags_NoHide)
        .value("NoClip",               ImGuiTableColumnFlags_NoClip)
        .value("NoSort",               ImGuiTableColumnFlags_NoSort)
        .value("NoSortAscending",      ImGuiTableColumnFlags_NoSortAscending)
        .value("NoSortDescending",     ImGuiTableColumnFlags_NoSortDescending)
        .value("NoHeaderLabel",        ImGuiTableColumnFlags_NoHeaderLabel)
        .value("NoHeaderWidth",        ImGuiTableColumnFlags_NoHeaderWidth)
        .value("PreferSortAscending",  ImGuiTableColumnFlags_PreferSortAscending)
        .value("PreferSortDescending", ImGuiTableColumnFlags_PreferSortDescending)
        .value("IndentEnable",         ImGuiTableColumnFlags_IndentEnable)
        .value("IndentDisable",        ImGuiTableColumnFlags_IndentDisable)
        .value("IsEnabled",            ImGuiTableColumnFlags_IsEnabled)
        .value("IsVisible",            ImGuiTableColumnFlags_IsVisible)
        .value("IsSorted",             ImGuiTableColumnFlags_IsSorted)
        .value("IsHovered",            ImGuiTableColumnFlags_IsHovered)
        .value("WidthMask_",           ImGuiTableColumnFlags_WidthMask_)
        .value("IndentMask_",          ImGuiTableColumnFlags_IndentMask_)
        .value("StatusMask_",          ImGuiTableColumnFlags_StatusMask_)
        .value("NoDirectResize_",      ImGuiTableColumnFlags_NoDirectResize_)
    ;

    nb::enum_<ImGuiTableRowFlags_>(m, "ImGuiTableRowFlags")
        .value("NONE",    ImGuiTableRowFlags_None)
        .value("Headers", ImGuiTableRowFlags_Headers)
    ;

    nb::enum_<ImGuiTableBgTarget_>(m, "ImGuiTableBgTarget")
        .value("NONE",   ImGuiTableBgTarget_None)
        .value("RowBg0", ImGuiTableBgTarget_RowBg0)
        .value("RowBg1", ImGuiTableBgTarget_RowBg1)
        .value("CellBg", ImGuiTableBgTarget_CellBg)
    ;

    nb::enum_<ImGuiFocusedFlags_>(m, "ImGuiFocusedFlags")
        .value("NONE",                ImGuiFocusedFlags_None)
        .value("ChildWindows",        ImGuiFocusedFlags_ChildWindows)
        .value("RootWindow",          ImGuiFocusedFlags_RootWindow)
        .value("AnyWindow",           ImGuiFocusedFlags_AnyWindow)
        .value("NoPopupHierarchy",    ImGuiFocusedFlags_NoPopupHierarchy)
        .value("RootAndChildWindows", ImGuiFocusedFlags_RootAndChildWindows)
    ;

    nb::enum_<ImGuiHoveredFlags_>(m, "ImGuiHoveredFlags")
        .value("NONE",                         ImGuiHoveredFlags_None)
        .value("ChildWindows",                 ImGuiHoveredFlags_ChildWindows)
        .value("RootWindow",                   ImGuiHoveredFlags_RootWindow)
        .value("AnyWindow",                    ImGuiHoveredFlags_AnyWindow)
        .value("NoPopupHierarchy",             ImGuiHoveredFlags_NoPopupHierarchy)
        .value("AllowWhenBlockedByPopup",      ImGuiHoveredFlags_AllowWhenBlockedByPopup)
        .value("AllowWhenBlockedByActiveItem", ImGuiHoveredFlags_AllowWhenBlockedByActiveItem)
        .value("AllowWhenOverlapped",          ImGuiHoveredFlags_AllowWhenOverlapped)
        .value("AllowWhenDisabled",            ImGuiHoveredFlags_AllowWhenDisabled)
        .value("NoNavOverride",                ImGuiHoveredFlags_NoNavOverride)
        .value("RectOnly",                     ImGuiHoveredFlags_RectOnly)
        .value("RootAndChildWindows",          ImGuiHoveredFlags_RootAndChildWindows)
    ;

    nb::enum_<ImGuiDragDropFlags_>(m, "ImGuiDragDropFlags")
        .value("NONE",                     ImGuiDragDropFlags_None)
        .value("SourceNoPreviewTooltip",   ImGuiDragDropFlags_SourceNoPreviewTooltip)
        .value("SourceNoDisableHover",     ImGuiDragDropFlags_SourceNoDisableHover)
        .value("SourceNoHoldToOpenOthers", ImGuiDragDropFlags_SourceNoHoldToOpenOthers)
        .value("SourceAllowNullID",        ImGuiDragDropFlags_SourceAllowNullID)
        .value("SourceExtern",             ImGuiDragDropFlags_SourceExtern)
        .value("SourceAutoExpirePayload",  ImGuiDragDropFlags_SourceAutoExpirePayload)
        .value("AcceptBeforeDelivery",     ImGuiDragDropFlags_AcceptBeforeDelivery)
        .value("AcceptNoDrawDefaultRect",  ImGuiDragDropFlags_AcceptNoDrawDefaultRect)
        .value("AcceptNoPreviewTooltip",   ImGuiDragDropFlags_AcceptNoPreviewTooltip)
        .value("AcceptPeekOnly",           ImGuiDragDropFlags_AcceptPeekOnly)
    ;

    nb::enum_<ImGuiDataType_>(m, "ImGuiDataType")
        .value("S8",     ImGuiDataType_S8)
        .value("U8",     ImGuiDataType_U8)
        .value("S16",    ImGuiDataType_S16)
        .value("U16",    ImGuiDataType_U16)
        .value("S32",    ImGuiDataType_S32)
        .value("U32",    ImGuiDataType_U32)
        .value("S64",    ImGuiDataType_S64)
        .value("U64",    ImGuiDataType_U64)
        .value("Float",  ImGuiDataType_Float)
        .value("Double", ImGuiDataType_Double)
        .value("COUNT",  ImGuiDataType_COUNT)
    ;

    nb::enum_<ImGuiDir_>(m, "ImGuiDir")
        .value("NONE",  ImGuiDir_None)
        .value("Left",  ImGuiDir_Left)
        .value("Right", ImGuiDir_Right)
        .value("Up",    ImGuiDir_Up)
        .value("Down",  ImGuiDir_Down)
        .value("COUNT", ImGuiDir_COUNT)
    ;

    nb::enum_<ImGuiSortDirection_>(m, "ImGuiSortDirection")
        .value("NONE",       ImGuiSortDirection_None)
        .value("Ascending",  ImGuiSortDirection_Ascending)
        .value("Descending", ImGuiSortDirection_Descending)
    ;

    nb::enum_<ImGuiKey_>(m, "ImGuiKey")
        .value("NONE",               ImGuiKey_None)
        .value("Tab",                ImGuiKey_Tab)
        .value("LeftArrow",          ImGuiKey_LeftArrow)
        .value("RightArrow",         ImGuiKey_RightArrow)
        .value("UpArrow",            ImGuiKey_UpArrow)
        .value("DownArrow",          ImGuiKey_DownArrow)
        .value("PageUp",             ImGuiKey_PageUp)
        .value("PageDown",           ImGuiKey_PageDown)
        .value("Home",               ImGuiKey_Home)
        .value("End",                ImGuiKey_End)
        .value("Insert",             ImGuiKey_Insert)
        .value("Delete",             ImGuiKey_Delete)
        .value("Backspace",          ImGuiKey_Backspace)
        .value("Space",              ImGuiKey_Space)
        .value("Enter",              ImGuiKey_Enter)
        .value("Escape",             ImGuiKey_Escape)
        .value("LeftCtrl",           ImGuiKey_LeftCtrl)
        .value("LeftShift",          ImGuiKey_LeftShift)
        .value("LeftAlt",            ImGuiKey_LeftAlt)
        .value("LeftSuper",          ImGuiKey_LeftSuper)
        .value("RightCtrl",          ImGuiKey_RightCtrl)
        .value("RightShift",         ImGuiKey_RightShift)
        .value("RightAlt",           ImGuiKey_RightAlt)
        .value("RightSuper",         ImGuiKey_RightSuper)
        .value("Menu",               ImGuiKey_Menu)
        .value("0",                  ImGuiKey_0)
        .value("1",                  ImGuiKey_1)
        .value("2",                  ImGuiKey_2)
        .value("3",                  ImGuiKey_3)
        .value("4",                  ImGuiKey_4)
        .value("5",                  ImGuiKey_5)
        .value("6",                  ImGuiKey_6)
        .value("7",                  ImGuiKey_7)
        .value("8",                  ImGuiKey_8)
        .value("9",                  ImGuiKey_9)
        .value("A",                  ImGuiKey_A)
        .value("B",                  ImGuiKey_B)
        .value("C",                  ImGuiKey_C)
        .value("D",                  ImGuiKey_D)
        .value("E",                  ImGuiKey_E)
        .value("F",                  ImGuiKey_F)
        .value("G",                  ImGuiKey_G)
        .value("H",                  ImGuiKey_H)
        .value("I",                  ImGuiKey_I)
        .value("J",                  ImGuiKey_J)
        .value("K",                  ImGuiKey_K)
        .value("L",                  ImGuiKey_L)
        .value("M",                  ImGuiKey_M)
        .value("N",                  ImGuiKey_N)
        .value("O",                  ImGuiKey_O)
        .value("P",                  ImGuiKey_P)
        .value("Q",                  ImGuiKey_Q)
        .value("R",                  ImGuiKey_R)
        .value("S",                  ImGuiKey_S)
        .value("T",                  ImGuiKey_T)
        .value("U",                  ImGuiKey_U)
        .value("V",                  ImGuiKey_V)
        .value("W",                  ImGuiKey_W)
        .value("X",                  ImGuiKey_X)
        .value("Y",                  ImGuiKey_Y)
        .value("Z",                  ImGuiKey_Z)
        .value("F1",                 ImGuiKey_F1)
        .value("F2",                 ImGuiKey_F2)
        .value("F3",                 ImGuiKey_F3)
        .value("F4",                 ImGuiKey_F4)
        .value("F5",                 ImGuiKey_F5)
        .value("F6",                 ImGuiKey_F6)
        .value("F7",                 ImGuiKey_F7)
        .value("F8",                 ImGuiKey_F8)
        .value("F9",                 ImGuiKey_F9)
        .value("F10",                ImGuiKey_F10)
        .value("F11",                ImGuiKey_F11)
        .value("F12",                ImGuiKey_F12)
        .value("Apostrophe",         ImGuiKey_Apostrophe)
        .value("Comma",              ImGuiKey_Comma)
        .value("Minus",              ImGuiKey_Minus)
        .value("Period",             ImGuiKey_Period)
        .value("Slash",              ImGuiKey_Slash)
        .value("Semicolon",          ImGuiKey_Semicolon)
        .value("Equal",              ImGuiKey_Equal)
        .value("LeftBracket",        ImGuiKey_LeftBracket)
        .value("Backslash",          ImGuiKey_Backslash)
        .value("RightBracket",       ImGuiKey_RightBracket)
        .value("GraveAccent",        ImGuiKey_GraveAccent)
        .value("CapsLock",           ImGuiKey_CapsLock)
        .value("ScrollLock",         ImGuiKey_ScrollLock)
        .value("NumLock",            ImGuiKey_NumLock)
        .value("PrintScreen",        ImGuiKey_PrintScreen)
        .value("Pause",              ImGuiKey_Pause)
        .value("Keypad0",            ImGuiKey_Keypad0)
        .value("Keypad1",            ImGuiKey_Keypad1)
        .value("Keypad2",            ImGuiKey_Keypad2)
        .value("Keypad3",            ImGuiKey_Keypad3)
        .value("Keypad4",            ImGuiKey_Keypad4)
        .value("Keypad5",            ImGuiKey_Keypad5)
        .value("Keypad6",            ImGuiKey_Keypad6)
        .value("Keypad7",            ImGuiKey_Keypad7)
        .value("Keypad8",            ImGuiKey_Keypad8)
        .value("Keypad9",            ImGuiKey_Keypad9)
        .value("KeypadDecimal",      ImGuiKey_KeypadDecimal)
        .value("KeypadDivide",       ImGuiKey_KeypadDivide)
        .value("KeypadMultiply",     ImGuiKey_KeypadMultiply)
        .value("KeypadSubtract",     ImGuiKey_KeypadSubtract)
        .value("KeypadAdd",          ImGuiKey_KeypadAdd)
        .value("KeypadEnter",        ImGuiKey_KeypadEnter)
        .value("KeypadEqual",        ImGuiKey_KeypadEqual)
        .value("GamepadStart",       ImGuiKey_GamepadStart)
        .value("GamepadBack",        ImGuiKey_GamepadBack)
        .value("GamepadFaceUp",      ImGuiKey_GamepadFaceUp)
        .value("GamepadFaceDown",    ImGuiKey_GamepadFaceDown)
        .value("GamepadFaceLeft",    ImGuiKey_GamepadFaceLeft)
        .value("GamepadFaceRight",   ImGuiKey_GamepadFaceRight)
        .value("GamepadDpadUp",      ImGuiKey_GamepadDpadUp)
        .value("GamepadDpadDown",    ImGuiKey_GamepadDpadDown)
        .value("GamepadDpadLeft",    ImGuiKey_GamepadDpadLeft)
        .value("GamepadDpadRight",   ImGuiKey_GamepadDpadRight)
        .value("GamepadL1",          ImGuiKey_GamepadL1)
        .value("GamepadR1",          ImGuiKey_GamepadR1)
        .value("GamepadL2",          ImGuiKey_GamepadL2)
        .value("GamepadR2",          ImGuiKey_GamepadR2)
        .value("GamepadL3",          ImGuiKey_GamepadL3)
        .value("GamepadR3",          ImGuiKey_GamepadR3)
        .value("GamepadLStickUp",    ImGuiKey_GamepadLStickUp)
        .value("GamepadLStickDown",  ImGuiKey_GamepadLStickDown)
        .value("GamepadLStickLeft",  ImGuiKey_GamepadLStickLeft)
        .value("GamepadLStickRight", ImGuiKey_GamepadLStickRight)
        .value("GamepadRStickUp",    ImGuiKey_GamepadRStickUp)
        .value("GamepadRStickDown",  ImGuiKey_GamepadRStickDown)
        .value("GamepadRStickLeft",  ImGuiKey_GamepadRStickLeft)
        .value("GamepadRStickRight", ImGuiKey_GamepadRStickRight)
        .value("ModCtrl",            ImGuiKey_ModCtrl)
        .value("ModShift",           ImGuiKey_ModShift)
        .value("ModAlt",             ImGuiKey_ModAlt)
        .value("ModSuper",           ImGuiKey_ModSuper)
        .value("COUNT",              ImGuiKey_COUNT)
        .value("NamedKey_BEGIN",     ImGuiKey_NamedKey_BEGIN)
        .value("NamedKey_END",       ImGuiKey_NamedKey_END)
        .value("NamedKey_COUNT",     ImGuiKey_NamedKey_COUNT)
        .value("KeysData_SIZE",      ImGuiKey_KeysData_SIZE)
        .value("KeysData_OFFSET",    ImGuiKey_KeysData_OFFSET)
        .value("KeyPadEnter",        ImGuiKey_KeyPadEnter)
    ;

    nb::enum_<ImGuiModFlags_>(m, "ImGuiModFlags")
        .value("NONE",  ImGuiModFlags_None)
        .value("Ctrl",  ImGuiModFlags_Ctrl)
        .value("Shift", ImGuiModFlags_Shift)
        .value("Alt",   ImGuiModFlags_Alt)
        .value("Super", ImGuiModFlags_Super)
    ;

    nb::enum_<ImGuiNavInput_>(m, "ImGuiNavInput")
        .value("Activate",    ImGuiNavInput_Activate)
        .value("Cancel",      ImGuiNavInput_Cancel)
        .value("Input",       ImGuiNavInput_Input)
        .value("Menu",        ImGuiNavInput_Menu)
        .value("DpadLeft",    ImGuiNavInput_DpadLeft)
        .value("DpadRight",   ImGuiNavInput_DpadRight)
        .value("DpadUp",      ImGuiNavInput_DpadUp)
        .value("DpadDown",    ImGuiNavInput_DpadDown)
        .value("LStickLeft",  ImGuiNavInput_LStickLeft)
        .value("LStickRight", ImGuiNavInput_LStickRight)
        .value("LStickUp",    ImGuiNavInput_LStickUp)
        .value("LStickDown",  ImGuiNavInput_LStickDown)
        .value("FocusPrev",   ImGuiNavInput_FocusPrev)
        .value("FocusNext",   ImGuiNavInput_FocusNext)
        .value("TweakSlow",   ImGuiNavInput_TweakSlow)
        .value("TweakFast",   ImGuiNavInput_TweakFast)
        .value("KeyLeft_",    ImGuiNavInput_KeyLeft_)
        .value("KeyRight_",   ImGuiNavInput_KeyRight_)
        .value("KeyUp_",      ImGuiNavInput_KeyUp_)
        .value("KeyDown_",    ImGuiNavInput_KeyDown_)
        .value("COUNT",       ImGuiNavInput_COUNT)
    ;

    nb::enum_<ImGuiConfigFlags_>(m, "ImGuiConfigFlags")
        .value("NONE",                 ImGuiConfigFlags_None)
        .value("NavEnableKeyboard",    ImGuiConfigFlags_NavEnableKeyboard)
        .value("NavEnableGamepad",     ImGuiConfigFlags_NavEnableGamepad)
        .value("NavEnableSetMousePos", ImGuiConfigFlags_NavEnableSetMousePos)
        .value("NavNoCaptureKeyboard", ImGuiConfigFlags_NavNoCaptureKeyboard)
        .value("NoMouse",              ImGuiConfigFlags_NoMouse)
        .value("NoMouseCursorChange",  ImGuiConfigFlags_NoMouseCursorChange)
        .value("IsSRGB",               ImGuiConfigFlags_IsSRGB)
        .value("IsTouchScreen",        ImGuiConfigFlags_IsTouchScreen)
    ;

    nb::enum_<ImGuiBackendFlags_>(m, "ImGuiBackendFlags")
        .value("NONE",                 ImGuiBackendFlags_None)
        .value("HasGamepad",           ImGuiBackendFlags_HasGamepad)
        .value("HasMouseCursors",      ImGuiBackendFlags_HasMouseCursors)
        .value("HasSetMousePos",       ImGuiBackendFlags_HasSetMousePos)
        .value("RendererHasVtxOffset", ImGuiBackendFlags_RendererHasVtxOffset)
    ;

    nb::enum_<ImGuiCol_>(m, "ImGuiCol")
        .value("Text",                  ImGuiCol_Text)
        .value("TextDisabled",          ImGuiCol_TextDisabled)
        .value("WindowBg",              ImGuiCol_WindowBg)
        .value("ChildBg",               ImGuiCol_ChildBg)
        .value("PopupBg",               ImGuiCol_PopupBg)
        .value("Border",                ImGuiCol_Border)
        .value("BorderShadow",          ImGuiCol_BorderShadow)
        .value("FrameBg",               ImGuiCol_FrameBg)
        .value("FrameBgHovered",        ImGuiCol_FrameBgHovered)
        .value("FrameBgActive",         ImGuiCol_FrameBgActive)
        .value("TitleBg",               ImGuiCol_TitleBg)
        .value("TitleBgActive",         ImGuiCol_TitleBgActive)
        .value("TitleBgCollapsed",      ImGuiCol_TitleBgCollapsed)
        .value("MenuBarBg",             ImGuiCol_MenuBarBg)
        .value("ScrollbarBg",           ImGuiCol_ScrollbarBg)
        .value("ScrollbarGrab",         ImGuiCol_ScrollbarGrab)
        .value("ScrollbarGrabHovered",  ImGuiCol_ScrollbarGrabHovered)
        .value("ScrollbarGrabActive",   ImGuiCol_ScrollbarGrabActive)
        .value("CheckMark",             ImGuiCol_CheckMark)
        .value("SliderGrab",            ImGuiCol_SliderGrab)
        .value("SliderGrabActive",      ImGuiCol_SliderGrabActive)
        .value("Button",                ImGuiCol_Button)
        .value("ButtonHovered",         ImGuiCol_ButtonHovered)
        .value("ButtonActive",          ImGuiCol_ButtonActive)
        .value("Header",                ImGuiCol_Header)
        .value("HeaderHovered",         ImGuiCol_HeaderHovered)
        .value("HeaderActive",          ImGuiCol_HeaderActive)
        .value("Separator",             ImGuiCol_Separator)
        .value("SeparatorHovered",      ImGuiCol_SeparatorHovered)
        .value("SeparatorActive",       ImGuiCol_SeparatorActive)
        .value("ResizeGrip",            ImGuiCol_ResizeGrip)
        .value("ResizeGripHovered",     ImGuiCol_ResizeGripHovered)
        .value("ResizeGripActive",      ImGuiCol_ResizeGripActive)
        .value("Tab",                   ImGuiCol_Tab)
        .value("TabHovered",            ImGuiCol_TabHovered)
        .value("TabActive",             ImGuiCol_TabActive)
        .value("TabUnfocused",          ImGuiCol_TabUnfocused)
        .value("TabUnfocusedActive",    ImGuiCol_TabUnfocusedActive)
        .value("PlotLines",             ImGuiCol_PlotLines)
        .value("PlotLinesHovered",      ImGuiCol_PlotLinesHovered)
        .value("PlotHistogram",         ImGuiCol_PlotHistogram)
        .value("PlotHistogramHovered",  ImGuiCol_PlotHistogramHovered)
        .value("TableHeaderBg",         ImGuiCol_TableHeaderBg)
        .value("TableBorderStrong",     ImGuiCol_TableBorderStrong)
        .value("TableBorderLight",      ImGuiCol_TableBorderLight)
        .value("TableRowBg",            ImGuiCol_TableRowBg)
        .value("TableRowBgAlt",         ImGuiCol_TableRowBgAlt)
        .value("TextSelectedBg",        ImGuiCol_TextSelectedBg)
        .value("DragDropTarget",        ImGuiCol_DragDropTarget)
        .value("NavHighlight",          ImGuiCol_NavHighlight)
        .value("NavWindowingHighlight", ImGuiCol_NavWindowingHighlight)
        .value("NavWindowingDimBg",     ImGuiCol_NavWindowingDimBg)
        .value("ModalWindowDimBg",      ImGuiCol_ModalWindowDimBg)
        .value("COUNT",                 ImGuiCol_COUNT)
    ;

    nb::enum_<ImGuiStyleVar_>(m, "ImGuiStyleVar")
        .value("Alpha",               ImGuiStyleVar_Alpha)
        .value("DisabledAlpha",       ImGuiStyleVar_DisabledAlpha)
        .value("WindowPadding",       ImGuiStyleVar_WindowPadding)
        .value("WindowRounding",      ImGuiStyleVar_WindowRounding)
        .value("WindowBorderSize",    ImGuiStyleVar_WindowBorderSize)
        .value("WindowMinSize",       ImGuiStyleVar_WindowMinSize)
        .value("WindowTitleAlign",    ImGuiStyleVar_WindowTitleAlign)
        .value("ChildRounding",       ImGuiStyleVar_ChildRounding)
        .value("ChildBorderSize",     ImGuiStyleVar_ChildBorderSize)
        .value("PopupRounding",       ImGuiStyleVar_PopupRounding)
        .value("PopupBorderSize",     ImGuiStyleVar_PopupBorderSize)
        .value("FramePadding",        ImGuiStyleVar_FramePadding)
        .value("FrameRounding",       ImGuiStyleVar_FrameRounding)
        .value("FrameBorderSize",     ImGuiStyleVar_FrameBorderSize)
        .value("ItemSpacing",         ImGuiStyleVar_ItemSpacing)
        .value("ItemInnerSpacing",    ImGuiStyleVar_ItemInnerSpacing)
        .value("IndentSpacing",       ImGuiStyleVar_IndentSpacing)
        .value("CellPadding",         ImGuiStyleVar_CellPadding)
        .value("ScrollbarSize",       ImGuiStyleVar_ScrollbarSize)
        .value("ScrollbarRounding",   ImGuiStyleVar_ScrollbarRounding)
        .value("GrabMinSize",         ImGuiStyleVar_GrabMinSize)
        .value("GrabRounding",        ImGuiStyleVar_GrabRounding)
        .value("TabRounding",         ImGuiStyleVar_TabRounding)
        .value("ButtonTextAlign",     ImGuiStyleVar_ButtonTextAlign)
        .value("SelectableTextAlign", ImGuiStyleVar_SelectableTextAlign)
        .value("COUNT",               ImGuiStyleVar_COUNT)
    ;

    nb::enum_<ImGuiButtonFlags_>(m, "ImGuiButtonFlags")
        .value("NONE",                ImGuiButtonFlags_None)
        .value("MouseButtonLeft",     ImGuiButtonFlags_MouseButtonLeft)
        .value("MouseButtonRight",    ImGuiButtonFlags_MouseButtonRight)
        .value("MouseButtonMiddle",   ImGuiButtonFlags_MouseButtonMiddle)
        .value("MouseButtonMask_",    ImGuiButtonFlags_MouseButtonMask_)
        .value("MouseButtonDefault_", ImGuiButtonFlags_MouseButtonDefault_)
    ;

    nb::enum_<ImGuiColorEditFlags_>(m, "ImGuiColorEditFlags")
        .value("NONE",             ImGuiColorEditFlags_None)
        .value("NoAlpha",          ImGuiColorEditFlags_NoAlpha)
        .value("NoPicker",         ImGuiColorEditFlags_NoPicker)
        .value("NoOptions",        ImGuiColorEditFlags_NoOptions)
        .value("NoSmallPreview",   ImGuiColorEditFlags_NoSmallPreview)
        .value("NoInputs",         ImGuiColorEditFlags_NoInputs)
        .value("NoTooltip",        ImGuiColorEditFlags_NoTooltip)
        .value("NoLabel",          ImGuiColorEditFlags_NoLabel)
        .value("NoSidePreview",    ImGuiColorEditFlags_NoSidePreview)
        .value("NoDragDrop",       ImGuiColorEditFlags_NoDragDrop)
        .value("NoBorder",         ImGuiColorEditFlags_NoBorder)
        .value("AlphaBar",         ImGuiColorEditFlags_AlphaBar)
        .value("AlphaPreview",     ImGuiColorEditFlags_AlphaPreview)
        .value("AlphaPreviewHalf", ImGuiColorEditFlags_AlphaPreviewHalf)
        .value("HDR",              ImGuiColorEditFlags_HDR)
        .value("DisplayRGB",       ImGuiColorEditFlags_DisplayRGB)
        .value("DisplayHSV",       ImGuiColorEditFlags_DisplayHSV)
        .value("DisplayHex",       ImGuiColorEditFlags_DisplayHex)
        .value("Uint8",            ImGuiColorEditFlags_Uint8)
        .value("Float",            ImGuiColorEditFlags_Float)
        .value("PickerHueBar",     ImGuiColorEditFlags_PickerHueBar)
        .value("PickerHueWheel",   ImGuiColorEditFlags_PickerHueWheel)
        .value("InputRGB",         ImGuiColorEditFlags_InputRGB)
        .value("InputHSV",         ImGuiColorEditFlags_InputHSV)
        .value("DefaultOptions_",  ImGuiColorEditFlags_DefaultOptions_)
        .value("DisplayMask_",     ImGuiColorEditFlags_DisplayMask_)
        .value("DataTypeMask_",    ImGuiColorEditFlags_DataTypeMask_)
        .value("PickerMask_",      ImGuiColorEditFlags_PickerMask_)
        .value("InputMask_",       ImGuiColorEditFlags_InputMask_)
    ;

    nb::enum_<ImGuiSliderFlags_>(m, "ImGuiSliderFlags")
        .value("NONE",            ImGuiSliderFlags_None)
        .value("AlwaysClamp",     ImGuiSliderFlags_AlwaysClamp)
        .value("Logarithmic",     ImGuiSliderFlags_Logarithmic)
        .value("NoRoundToFormat", ImGuiSliderFlags_NoRoundToFormat)
        .value("NoInput",         ImGuiSliderFlags_NoInput)
        .value("InvalidMask_",    ImGuiSliderFlags_InvalidMask_)
        .value("ClampOnInput",    ImGuiSliderFlags_ClampOnInput)
    ;

    nb::enum_<ImGuiMouseButton_>(m, "ImGuiMouseButton")
        .value("Left",   ImGuiMouseButton_Left)
        .value("Right",  ImGuiMouseButton_Right)
        .value("Middle", ImGuiMouseButton_Middle)
        .value("COUNT",  ImGuiMouseButton_COUNT)
    ;

    nb::enum_<ImGuiMouseCursor_>(m, "ImGuiMouseCursor")
        .value("NONE",       ImGuiMouseCursor_None)
        .value("Arrow",      ImGuiMouseCursor_Arrow)
        .value("TextInput",  ImGuiMouseCursor_TextInput)
        .value("ResizeAll",  ImGuiMouseCursor_ResizeAll)
        .value("ResizeNS",   ImGuiMouseCursor_ResizeNS)
        .value("ResizeEW",   ImGuiMouseCursor_ResizeEW)
        .value("ResizeNESW", ImGuiMouseCursor_ResizeNESW)
        .value("ResizeNWSE", ImGuiMouseCursor_ResizeNWSE)
        .value("Hand",       ImGuiMouseCursor_Hand)
        .value("NotAllowed", ImGuiMouseCursor_NotAllowed)
        .value("COUNT",      ImGuiMouseCursor_COUNT)
    ;

    nb::enum_<ImGuiCond_>(m, "ImGuiCond")
        .value("NONE",         ImGuiCond_None)
        .value("Always",       ImGuiCond_Always)
        .value("Once",         ImGuiCond_Once)
        .value("FirstUseEver", ImGuiCond_FirstUseEver)
        .value("Appearing",    ImGuiCond_Appearing)
    ;

    nb::enum_<ImDrawFlags_>(m, "ImDrawFlags")
        .value("NONE",                    ImDrawFlags_None)
        .value("Closed",                  ImDrawFlags_Closed)
        .value("RoundCornersTopLeft",     ImDrawFlags_RoundCornersTopLeft)
        .value("RoundCornersTopRight",    ImDrawFlags_RoundCornersTopRight)
        .value("RoundCornersBottomLeft",  ImDrawFlags_RoundCornersBottomLeft)
        .value("RoundCornersBottomRight", ImDrawFlags_RoundCornersBottomRight)
        .value("RoundCornersNone",        ImDrawFlags_RoundCornersNone)
        .value("RoundCornersTop",         ImDrawFlags_RoundCornersTop)
        .value("RoundCornersBottom",      ImDrawFlags_RoundCornersBottom)
        .value("RoundCornersLeft",        ImDrawFlags_RoundCornersLeft)
        .value("RoundCornersRight",       ImDrawFlags_RoundCornersRight)
        .value("RoundCornersAll",         ImDrawFlags_RoundCornersAll)
        .value("RoundCornersDefault_",    ImDrawFlags_RoundCornersDefault_)
        .value("RoundCornersMask_",       ImDrawFlags_RoundCornersMask_)
    ;

    nb::enum_<ImDrawListFlags_>(m, "ImDrawListFlags")
        .value("NONE",                   ImDrawListFlags_None)
        .value("AntiAliasedLines",       ImDrawListFlags_AntiAliasedLines)
        .value("AntiAliasedLinesUseTex", ImDrawListFlags_AntiAliasedLinesUseTex)
        .value("AntiAliasedFill",        ImDrawListFlags_AntiAliasedFill)
        .value("AllowVtxOffset",         ImDrawListFlags_AllowVtxOffset)
    ;

    nb::enum_<ImFontAtlasFlags_>(m, "ImFontAtlasFlags")
        .value("NONE",               ImFontAtlasFlags_None)
        .value("NoPowerOfTwoHeight", ImFontAtlasFlags_NoPowerOfTwoHeight)
        .value("NoMouseCursors",     ImFontAtlasFlags_NoMouseCursors)
        .value("NoBakedLines",       ImFontAtlasFlags_NoBakedLines)
    ;

    nb::enum_<ImGuiViewportFlags_>(m, "ImGuiViewportFlags")
        .value("NONE",              ImGuiViewportFlags_None)
        .value("IsPlatformWindow",  ImGuiViewportFlags_IsPlatformWindow)
        .value("IsPlatformMonitor", ImGuiViewportFlags_IsPlatformMonitor)
        .value("OwnedByApp",        ImGuiViewportFlags_OwnedByApp)
    ;

    nb::enum_<ImDrawCornerFlags_>(m, "ImDrawCornerFlags")
        .value("NONE",     ImDrawCornerFlags_None)
        .value("TopLeft",  ImDrawCornerFlags_TopLeft)
        .value("TopRight", ImDrawCornerFlags_TopRight)
        .value("BotLeft",  ImDrawCornerFlags_BotLeft)
        .value("BotRight", ImDrawCornerFlags_BotRight)
        .value("All",      ImDrawCornerFlags_All)
        .value("Top",      ImDrawCornerFlags_Top)
        .value("Bot",      ImDrawCornerFlags_Bot)
        .value("Left",     ImDrawCornerFlags_Left)
        .value("Right",    ImDrawCornerFlags_Right)
    ;

    nb::enum_<ImGuiKeyModFlags_>(m, "ImGuiKeyModFlags")
        .value("NONE",  ImGuiKeyModFlags_None)
        .value("Ctrl",  ImGuiKeyModFlags_Ctrl)
        .value("Shift", ImGuiKeyModFlags_Shift)
        .value("Alt",   ImGuiKeyModFlags_Alt)
        .value("Super", ImGuiKeyModFlags_Super)
    ;

    nb::enum_<ImGuiItemFlags_>(m, "ImGuiItemFlags")
        .value("NONE",                     ImGuiItemFlags_None)
        .value("NoTabStop",                ImGuiItemFlags_NoTabStop)
        .value("ButtonRepeat",             ImGuiItemFlags_ButtonRepeat)
        .value("Disabled",                 ImGuiItemFlags_Disabled)
        .value("NoNav",                    ImGuiItemFlags_NoNav)
        .value("NoNavDefaultFocus",        ImGuiItemFlags_NoNavDefaultFocus)
        .value("SelectableDontClosePopup", ImGuiItemFlags_SelectableDontClosePopup)
        .value("MixedValue",               ImGuiItemFlags_MixedValue)
        .value("ReadOnly",                 ImGuiItemFlags_ReadOnly)
        .value("Inputable",                ImGuiItemFlags_Inputable)
    ;

    nb::enum_<ImGuiItemStatusFlags_>(m, "ImGuiItemStatusFlags")
        .value("NONE",             ImGuiItemStatusFlags_None)
        .value("HoveredRect",      ImGuiItemStatusFlags_HoveredRect)
        .value("HasDisplayRect",   ImGuiItemStatusFlags_HasDisplayRect)
        .value("Edited",           ImGuiItemStatusFlags_Edited)
        .value("ToggledSelection", ImGuiItemStatusFlags_ToggledSelection)
        .value("ToggledOpen",      ImGuiItemStatusFlags_ToggledOpen)
        .value("HasDeactivated",   ImGuiItemStatusFlags_HasDeactivated)
        .value("Deactivated",      ImGuiItemStatusFlags_Deactivated)
        .value("HoveredWindow",    ImGuiItemStatusFlags_HoveredWindow)
        .value("FocusedByTabbing", ImGuiItemStatusFlags_FocusedByTabbing)
    ;

    nb::enum_<ImGuiSeparatorFlags_>(m, "ImGuiSeparatorFlags")
        .value("NONE",           ImGuiSeparatorFlags_None)
        .value("Horizontal",     ImGuiSeparatorFlags_Horizontal)
        .value("Vertical",       ImGuiSeparatorFlags_Vertical)
        .value("SpanAllColumns", ImGuiSeparatorFlags_SpanAllColumns)
    ;

    nb::enum_<ImGuiTextFlags_>(m, "ImGuiTextFlags")
        .value("NONE",                       ImGuiTextFlags_None)
        .value("NoWidthForLargeClippedText", ImGuiTextFlags_NoWidthForLargeClippedText)
    ;

    nb::enum_<ImGuiTooltipFlags_>(m, "ImGuiTooltipFlags")
        .value("NONE",                    ImGuiTooltipFlags_None)
        .value("OverridePreviousTooltip", ImGuiTooltipFlags_OverridePreviousTooltip)
    ;

    nb::enum_<ImGuiLayoutType_>(m, "ImGuiLayoutType")
        .value("Horizontal", ImGuiLayoutType_Horizontal)
        .value("Vertical",   ImGuiLayoutType_Vertical)
    ;

    nb::enum_<ImGuiLogType>(m, "ImGuiLogType")
        .value("NONE",      ImGuiLogType_None)
        .value("TTY",       ImGuiLogType_TTY)
        .value("File",      ImGuiLogType_File)
        .value("Buffer",    ImGuiLogType_Buffer)
        .value("Clipboard", ImGuiLogType_Clipboard)
    ;

    nb::enum_<ImGuiAxis>(m, "ImGuiAxis")
        .value("NONE", ImGuiAxis_None)
        .value("X",    ImGuiAxis_X)
        .value("Y",    ImGuiAxis_Y)
    ;

    nb::enum_<ImGuiPlotType>(m, "ImGuiPlotType")
        .value("Lines",     ImGuiPlotType_Lines)
        .value("Histogram", ImGuiPlotType_Histogram)
    ;

    nb::enum_<ImGuiPopupPositionPolicy>(m, "ImGuiPopupPositionPolicy")
        .value("Default",  ImGuiPopupPositionPolicy_Default)
        .value("ComboBox", ImGuiPopupPositionPolicy_ComboBox)
        .value("Tooltip",  ImGuiPopupPositionPolicy_Tooltip)
    ;

    nb::enum_<ImGuiNextWindowDataFlags_>(m, "ImGuiNextWindowDataFlags")
        .value("NONE",              ImGuiNextWindowDataFlags_None)
        .value("HasPos",            ImGuiNextWindowDataFlags_HasPos)
        .value("HasSize",           ImGuiNextWindowDataFlags_HasSize)
        .value("HasContentSize",    ImGuiNextWindowDataFlags_HasContentSize)
        .value("HasCollapsed",      ImGuiNextWindowDataFlags_HasCollapsed)
        .value("HasSizeConstraint", ImGuiNextWindowDataFlags_HasSizeConstraint)
        .value("HasFocus",          ImGuiNextWindowDataFlags_HasFocus)
        .value("HasBgAlpha",        ImGuiNextWindowDataFlags_HasBgAlpha)
        .value("HasScroll",         ImGuiNextWindowDataFlags_HasScroll)
    ;

    nb::enum_<ImGuiNextItemDataFlags_>(m, "ImGuiNextItemDataFlags")
        .value("NONE",     ImGuiNextItemDataFlags_None)
        .value("HasWidth", ImGuiNextItemDataFlags_HasWidth)
        .value("HasOpen",  ImGuiNextItemDataFlags_HasOpen)
    ;

    nb::enum_<ImGuiInputEventType>(m, "ImGuiInputEventType")
        .value("NONE",        ImGuiInputEventType_None)
        .value("MousePos",    ImGuiInputEventType_MousePos)
        .value("MouseWheel",  ImGuiInputEventType_MouseWheel)
        .value("MouseButton", ImGuiInputEventType_MouseButton)
        .value("Key",         ImGuiInputEventType_Key)
        .value("Text",        ImGuiInputEventType_Text)
        .value("Focus",       ImGuiInputEventType_Focus)
        .value("COUNT",       ImGuiInputEventType_COUNT)
    ;

    nb::enum_<ImGuiInputSource>(m, "ImGuiInputSource")
        .value("NONE",      ImGuiInputSource_None)
        .value("Mouse",     ImGuiInputSource_Mouse)
        .value("Keyboard",  ImGuiInputSource_Keyboard)
        .value("Gamepad",   ImGuiInputSource_Gamepad)
        .value("Clipboard", ImGuiInputSource_Clipboard)
        .value("Nav",       ImGuiInputSource_Nav)
        .value("COUNT",     ImGuiInputSource_COUNT)
    ;

    nb::enum_<ImGuiNavReadMode>(m, "ImGuiNavReadMode")
        .value("Down",       ImGuiNavReadMode_Down)
        .value("Pressed",    ImGuiNavReadMode_Pressed)
        .value("Released",   ImGuiNavReadMode_Released)
        .value("Repeat",     ImGuiNavReadMode_Repeat)
        .value("RepeatSlow", ImGuiNavReadMode_RepeatSlow)
        .value("RepeatFast", ImGuiNavReadMode_RepeatFast)
    ;

    nb::enum_<ImGuiActivateFlags_>(m, "ImGuiActivateFlags")
        .value("NONE",               ImGuiActivateFlags_None)
        .value("PreferInput",        ImGuiActivateFlags_PreferInput)
        .value("PreferTweak",        ImGuiActivateFlags_PreferTweak)
        .value("TryToPreserveState", ImGuiActivateFlags_TryToPreserveState)
    ;

    nb::enum_<ImGuiScrollFlags_>(m, "ImGuiScrollFlags")
        .value("NONE",               ImGuiScrollFlags_None)
        .value("KeepVisibleEdgeX",   ImGuiScrollFlags_KeepVisibleEdgeX)
        .value("KeepVisibleEdgeY",   ImGuiScrollFlags_KeepVisibleEdgeY)
        .value("KeepVisibleCenterX", ImGuiScrollFlags_KeepVisibleCenterX)
        .value("KeepVisibleCenterY", ImGuiScrollFlags_KeepVisibleCenterY)
        .value("AlwaysCenterX",      ImGuiScrollFlags_AlwaysCenterX)
        .value("AlwaysCenterY",      ImGuiScrollFlags_AlwaysCenterY)
        .value("NoScrollParent",     ImGuiScrollFlags_NoScrollParent)
        .value("MaskX_",             ImGuiScrollFlags_MaskX_)
        .value("MaskY_",             ImGuiScrollFlags_MaskY_)
    ;

    nb::enum_<ImGuiNavHighlightFlags_>(m, "ImGuiNavHighlightFlags")
        .value("NONE",        ImGuiNavHighlightFlags_None)
        .value("TypeDefault", ImGuiNavHighlightFlags_TypeDefault)
        .value("TypeThin",    ImGuiNavHighlightFlags_TypeThin)
        .value("AlwaysDraw",  ImGuiNavHighlightFlags_AlwaysDraw)
        .value("NoRounding",  ImGuiNavHighlightFlags_NoRounding)
    ;

    nb::enum_<ImGuiNavDirSourceFlags_>(m, "ImGuiNavDirSourceFlags")
        .value("NONE",        ImGuiNavDirSourceFlags_None)
        .value("RawKeyboard", ImGuiNavDirSourceFlags_RawKeyboard)
        .value("Keyboard",    ImGuiNavDirSourceFlags_Keyboard)
        .value("PadDPad",     ImGuiNavDirSourceFlags_PadDPad)
        .value("PadLStick",   ImGuiNavDirSourceFlags_PadLStick)
    ;

    nb::enum_<ImGuiNavMoveFlags_>(m, "ImGuiNavMoveFlags")
        .value("NONE",                ImGuiNavMoveFlags_None)
        .value("LoopX",               ImGuiNavMoveFlags_LoopX)
        .value("LoopY",               ImGuiNavMoveFlags_LoopY)
        .value("WrapX",               ImGuiNavMoveFlags_WrapX)
        .value("WrapY",               ImGuiNavMoveFlags_WrapY)
        .value("AllowCurrentNavId",   ImGuiNavMoveFlags_AllowCurrentNavId)
        .value("AlsoScoreVisibleSet", ImGuiNavMoveFlags_AlsoScoreVisibleSet)
        .value("ScrollToEdgeY",       ImGuiNavMoveFlags_ScrollToEdgeY)
        .value("Forwarded",           ImGuiNavMoveFlags_Forwarded)
        .value("DebugNoResult",       ImGuiNavMoveFlags_DebugNoResult)
        .value("FocusApi",            ImGuiNavMoveFlags_FocusApi)
        .value("Tabbing",             ImGuiNavMoveFlags_Tabbing)
        .value("Activate",            ImGuiNavMoveFlags_Activate)
        .value("DontSetNavHighlight", ImGuiNavMoveFlags_DontSetNavHighlight)
    ;

    nb::enum_<ImGuiNavLayer>(m, "ImGuiNavLayer")
        .value("Main",  ImGuiNavLayer_Main)
        .value("Menu",  ImGuiNavLayer_Menu)
        .value("COUNT", ImGuiNavLayer_COUNT)
    ;

    nb::enum_<ImGuiContextHookType>(m, "ImGuiContextHookType")
        .value("NewFramePre",     ImGuiContextHookType_NewFramePre)
        .value("NewFramePost",    ImGuiContextHookType_NewFramePost)
        .value("EndFramePre",     ImGuiContextHookType_EndFramePre)
        .value("EndFramePost",    ImGuiContextHookType_EndFramePost)
        .value("RenderPre",       ImGuiContextHookType_RenderPre)
        .value("RenderPost",      ImGuiContextHookType_RenderPost)
        .value("Shutdown",        ImGuiContextHookType_Shutdown)
        .value("PendingRemoval_", ImGuiContextHookType_PendingRemoval_)
    ;

}
