#include "types.hpp"
#include <nanobind/stl/string.h>

namespace nb = nanobind;

void imgui_def_types(nb::module_ & m) {

    nb::class_<ImGuiIO>(m, "ImGuiIO")
        .def_readwrite("ConfigFlags", &ImGuiIO::ConfigFlags)
        .def_readwrite("BackendFlags", &ImGuiIO::BackendFlags)
        .def_readwrite("DisplaySize", &ImGuiIO::DisplaySize)
        .def_readwrite("DeltaTime", &ImGuiIO::DeltaTime)
        .def_readwrite("IniSavingRate", &ImGuiIO::IniSavingRate)
        // .def_property_readonly("IniFilename", [](ImGuiIO const & self) { return self.IniFilename; })
        .def_property("IniFilename", [](ImGuiIO const & self) { return self.IniFilename; }, [](ImGuiIO & self, nb::str & value) { self.IniFilename = value.c_str(); } )
        .def_property_readonly("LogFilename", [](ImGuiIO const & self) { return self.LogFilename; })
        .def_readwrite("MouseDoubleClickTime", &ImGuiIO::MouseDoubleClickTime)
        .def_readwrite("MouseDoubleClickMaxDist", &ImGuiIO::MouseDoubleClickMaxDist)
        .def_readwrite("MouseDragThreshold", &ImGuiIO::MouseDragThreshold)
        .def_readwrite("KeyRepeatDelay", &ImGuiIO::KeyRepeatDelay)
        .def_readwrite("KeyRepeatRate", &ImGuiIO::KeyRepeatRate)
        .def_readwrite("FontGlobalScale", &ImGuiIO::FontGlobalScale)
        .def_readwrite("FontAllowUserScaling", &ImGuiIO::FontAllowUserScaling)
        .def_readwrite("DisplayFramebufferScale", &ImGuiIO::DisplayFramebufferScale)
        .def_readwrite("MouseDrawCursor", &ImGuiIO::MouseDrawCursor)
        .def_readwrite("ConfigMacOSXBehaviors", &ImGuiIO::ConfigMacOSXBehaviors)
        .def_readwrite("ConfigInputTrickleEventQueue", &ImGuiIO::ConfigInputTrickleEventQueue)
        .def_readwrite("ConfigInputTextCursorBlink", &ImGuiIO::ConfigInputTextCursorBlink)
        .def_readwrite("ConfigDragClickToInputText", &ImGuiIO::ConfigDragClickToInputText)
        .def_readwrite("ConfigWindowsResizeFromEdges", &ImGuiIO::ConfigWindowsResizeFromEdges)
        .def_readwrite("ConfigWindowsMoveFromTitleBarOnly", &ImGuiIO::ConfigWindowsMoveFromTitleBarOnly)
        .def_readwrite("ConfigMemoryCompactTimer", &ImGuiIO::ConfigMemoryCompactTimer)
        .def_property_readonly("BackendPlatformName", [](ImGuiIO const & self) { return self.BackendPlatformName; })
        .def_property_readonly("BackendRendererName", [](ImGuiIO const & self) { return self.BackendRendererName; })
        .def_readwrite("WantCaptureMouse", &ImGuiIO::WantCaptureMouse)
        .def_readwrite("WantCaptureKeyboard", &ImGuiIO::WantCaptureKeyboard)
        .def_readwrite("WantTextInput", &ImGuiIO::WantTextInput)
        .def_readwrite("WantSetMousePos", &ImGuiIO::WantSetMousePos)
        .def_readwrite("WantSaveIniSettings", &ImGuiIO::WantSaveIniSettings)
        .def_readwrite("NavActive", &ImGuiIO::NavActive)
        .def_readwrite("NavVisible", &ImGuiIO::NavVisible)
        .def_readwrite("Framerate", &ImGuiIO::Framerate)
        .def_readwrite("MetricsRenderVertices", &ImGuiIO::MetricsRenderVertices)
        .def_readwrite("MetricsRenderIndices", &ImGuiIO::MetricsRenderIndices)
        .def_readwrite("MetricsRenderWindows", &ImGuiIO::MetricsRenderWindows)
        .def_readwrite("MetricsActiveWindows", &ImGuiIO::MetricsActiveWindows)
        .def_readwrite("MetricsActiveAllocations", &ImGuiIO::MetricsActiveAllocations)
        .def_readwrite("MouseDelta", &ImGuiIO::MouseDelta)
        .def_readwrite("MousePos", &ImGuiIO::MousePos)
        .def_readwrite("MouseWheel", &ImGuiIO::MouseWheel)
        .def_readwrite("MouseWheelH", &ImGuiIO::MouseWheelH)
        .def_readwrite("KeyCtrl", &ImGuiIO::KeyCtrl)
        .def_readwrite("KeyShift", &ImGuiIO::KeyShift)
        .def_readwrite("KeyAlt", &ImGuiIO::KeyAlt)
        .def_readwrite("KeySuper", &ImGuiIO::KeySuper)
        .def_readwrite("KeyMods", &ImGuiIO::KeyMods)
        .def_readwrite("WantCaptureMouseUnlessPopupClose", &ImGuiIO::WantCaptureMouseUnlessPopupClose)
        .def_readwrite("MousePosPrev", &ImGuiIO::MousePosPrev)
        .def_readwrite("PenPressure", &ImGuiIO::PenPressure)
        .def_readwrite("AppFocusLost", &ImGuiIO::AppFocusLost)
        .def_readwrite("BackendUsingLegacyKeyArrays", &ImGuiIO::BackendUsingLegacyKeyArrays)
        .def_readwrite("BackendUsingLegacyNavInputArray", &ImGuiIO::BackendUsingLegacyNavInputArray)
        .def_readwrite("InputQueueSurrogate", &ImGuiIO::InputQueueSurrogate)
        .def_readwrite("InputQueueCharacters", &ImGuiIO::InputQueueCharacters)
        .def(nb::init<>())
        .def("AddKeyEvent",            &ImGuiIO::AddKeyEvent)
        .def("AddKeyAnalogEvent",      &ImGuiIO::AddKeyAnalogEvent)
        .def("AddMousePosEvent",       &ImGuiIO::AddMousePosEvent)
        .def("AddMouseButtonEvent",    &ImGuiIO::AddMouseButtonEvent)
        .def("AddMouseWheelEvent",     &ImGuiIO::AddMouseWheelEvent)
        .def("AddFocusEvent",          &ImGuiIO::AddFocusEvent)
        .def("AddInputCharacter",      &ImGuiIO::AddInputCharacter)
        .def("AddInputCharacterUTF16", &ImGuiIO::AddInputCharacterUTF16)
        .def("ClearInputCharacters",   &ImGuiIO::ClearInputCharacters)
        .def("ClearInputKeys",         &ImGuiIO::ClearInputKeys)
        .def("SetKeyEventNativeData",  &ImGuiIO::SetKeyEventNativeData)
    ;

    nb::class_<ImGuiStyle>(m, "ImGuiStyle")
        .def_readwrite("Alpha", &ImGuiStyle::Alpha)
        .def_readwrite("DisabledAlpha", &ImGuiStyle::DisabledAlpha)
        .def_readwrite("WindowPadding", &ImGuiStyle::WindowPadding)
        .def_readwrite("WindowRounding", &ImGuiStyle::WindowRounding)
        .def_readwrite("WindowBorderSize", &ImGuiStyle::WindowBorderSize)
        .def_readwrite("WindowMinSize", &ImGuiStyle::WindowMinSize)
        .def_readwrite("WindowTitleAlign", &ImGuiStyle::WindowTitleAlign)
        .def_readwrite("WindowMenuButtonPosition", &ImGuiStyle::WindowMenuButtonPosition)
        .def_readwrite("ChildRounding", &ImGuiStyle::ChildRounding)
        .def_readwrite("ChildBorderSize", &ImGuiStyle::ChildBorderSize)
        .def_readwrite("PopupRounding", &ImGuiStyle::PopupRounding)
        .def_readwrite("PopupBorderSize", &ImGuiStyle::PopupBorderSize)
        .def_readwrite("FramePadding", &ImGuiStyle::FramePadding)
        .def_readwrite("FrameRounding", &ImGuiStyle::FrameRounding)
        .def_readwrite("FrameBorderSize", &ImGuiStyle::FrameBorderSize)
        .def_readwrite("ItemSpacing", &ImGuiStyle::ItemSpacing)
        .def_readwrite("ItemInnerSpacing", &ImGuiStyle::ItemInnerSpacing)
        .def_readwrite("CellPadding", &ImGuiStyle::CellPadding)
        .def_readwrite("TouchExtraPadding", &ImGuiStyle::TouchExtraPadding)
        .def_readwrite("IndentSpacing", &ImGuiStyle::IndentSpacing)
        .def_readwrite("ColumnsMinSpacing", &ImGuiStyle::ColumnsMinSpacing)
        .def_readwrite("ScrollbarSize", &ImGuiStyle::ScrollbarSize)
        .def_readwrite("ScrollbarRounding", &ImGuiStyle::ScrollbarRounding)
        .def_readwrite("GrabMinSize", &ImGuiStyle::GrabMinSize)
        .def_readwrite("GrabRounding", &ImGuiStyle::GrabRounding)
        .def_readwrite("LogSliderDeadzone", &ImGuiStyle::LogSliderDeadzone)
        .def_readwrite("TabRounding", &ImGuiStyle::TabRounding)
        .def_readwrite("TabBorderSize", &ImGuiStyle::TabBorderSize)
        .def_readwrite("TabMinWidthForCloseButton", &ImGuiStyle::TabMinWidthForCloseButton)
        .def_readwrite("ColorButtonPosition", &ImGuiStyle::ColorButtonPosition)
        .def_readwrite("ButtonTextAlign", &ImGuiStyle::ButtonTextAlign)
        .def_readwrite("SelectableTextAlign", &ImGuiStyle::SelectableTextAlign)
        .def_readwrite("DisplayWindowPadding", &ImGuiStyle::DisplayWindowPadding)
        .def_readwrite("DisplaySafeAreaPadding", &ImGuiStyle::DisplaySafeAreaPadding)
        .def_readwrite("MouseCursorScale", &ImGuiStyle::MouseCursorScale)
        .def_readwrite("AntiAliasedLines", &ImGuiStyle::AntiAliasedLines)
        .def_readwrite("AntiAliasedLinesUseTex", &ImGuiStyle::AntiAliasedLinesUseTex)
        .def_readwrite("AntiAliasedFill", &ImGuiStyle::AntiAliasedFill)
        .def_readwrite("CurveTessellationTol", &ImGuiStyle::CurveTessellationTol)
        .def_readwrite("CircleTessellationMaxError", &ImGuiStyle::CircleTessellationMaxError)
        .def(nb::init<>())
        .def("ScaleAllSizes", &ImGuiStyle::ScaleAllSizes)
    ;

    nb::class_<ImVec2>(m, "ImVec2")
        .def_readwrite("x", &ImVec2::x)
        .def_readwrite("y", &ImVec2::y)
        .def(nb::init<>())
        .def(nb::init<float, float>())
        .def(nb::init_implicit<const nanobind::tuple &>())
        .def("__getitem__", nb::overload_cast<size_t>(&ImVec2::operator[], nb::const_))
        .def("__getitem__", nb::overload_cast<size_t>(&ImVec2::operator[]))
        .def("__setitem__", [](ImVec2 & self, size_t idx, const float & value) { self[idx] = value; })
        .def("__repr__",    &ImVec2::to_string)
    ;

    nb::class_<ImVec4>(m, "ImVec4")
        .def_readwrite("x", &ImVec4::x)
        .def_readwrite("y", &ImVec4::y)
        .def_readwrite("z", &ImVec4::z)
        .def_readwrite("w", &ImVec4::w)
        .def(nb::init<>())
        .def(nb::init<float, float, float, float>())
        .def(nb::init_implicit<const nanobind::tuple &>())
        .def("__repr__",    &ImVec4::to_string)
    ;

    nb::class_<ImRect>(m, "ImRect")
        .def_readwrite("Min", &ImRect::Min)
        .def_readwrite("Max", &ImRect::Max)
        .def(nb::init<>())
        .def(nb::init<const ImVec2 &, const ImVec2 &>())
        .def(nb::init<const ImVec4 &>())
        .def(nb::init<float, float, float, float>())
        .def("GetCenter",    &ImRect::GetCenter)
        .def("GetSize",      &ImRect::GetSize)
        .def("GetWidth",     &ImRect::GetWidth)
        .def("GetHeight",    &ImRect::GetHeight)
        .def("GetArea",      &ImRect::GetArea)
        .def("GetTL",        &ImRect::GetTL)
        .def("GetTR",        &ImRect::GetTR)
        .def("GetBL",        &ImRect::GetBL)
        .def("GetBR",        &ImRect::GetBR)
        .def("Contains",     nb::overload_cast<const ImVec2 &>(&ImRect::Contains, nb::const_))
        .def("Contains",     nb::overload_cast<const ImRect &>(&ImRect::Contains, nb::const_))
        .def("Overlaps",     &ImRect::Overlaps)
        .def("Add",          nb::overload_cast<const ImVec2 &>(&ImRect::Add))
        .def("Add",          nb::overload_cast<const ImRect &>(&ImRect::Add))
        .def("Expand",       nb::overload_cast<const float>(&ImRect::Expand))
        .def("Expand",       nb::overload_cast<const ImVec2 &>(&ImRect::Expand))
        .def("Translate",    &ImRect::Translate)
        .def("TranslateX",   &ImRect::TranslateX)
        .def("TranslateY",   &ImRect::TranslateY)
        .def("ClipWith",     &ImRect::ClipWith)
        .def("ClipWithFull", &ImRect::ClipWithFull)
        .def("Floor",        &ImRect::Floor)
        .def("IsInverted",   &ImRect::IsInverted)
        .def("ToVec4",       &ImRect::ToVec4)
    ;

}

